<a href="https://colab.research.google.com/github/diwakarojha/Python_ML_Basics/blob/main/3_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.DataFrame()
df['dttm']=pd.date_range(start='12-30-2020',periods=12,freq='5H')

In [4]:
df['dttm'].dt.minute
df['dttm'].dt.hour
df['dttm'].dt.date
df['dttm'].dt.year

0     2020
1     2020
2     2020
3     2020
4     2020
5     2020
6     2020
7     2020
8     2020
9     2020
10    2021
11    2021
Name: dttm, dtype: int64

In [ ]:
d1=np.dtype([('age',np.int16)])

X=np.array([1,2,3,4])

In [ ]:
X.itemsize

8

In [ ]:
np.arange(4).reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [ ]:
np.empty(2)

array([1.30507164e-316, 0.00000000e+000])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [ ]:
np.logspace(0,100,10)

array([1.00000000e+000, 1.29154967e+011, 1.66810054e+022, 2.15443469e+033,
       2.78255940e+044, 3.59381366e+055, 4.64158883e+066, 5.99484250e+077,
       7.74263683e+088, 1.00000000e+100])

In [ ]:
arr=np.arange(100).reshape(5,20)

In [ ]:
arr[...,2:-5]

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
       [42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74],
       [82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94]])

In [ ]:
x=np.array([[1,2],[3,4],[5,6]])
x[[True,1,True],[0,1,0]]


array([3, 4, 3])

In [ ]:
for z in x.flat:
  print(z)

1
2
3
4
5
6


In [ ]:
x.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
x.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
x.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
x.squeeze()

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
x=np.array([[1,2,3]])
y=np.array([[4,5,6]])

np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x.resize((1,5))

In [ ]:
np.unique(x)

array([0, 1, 2, 3])

In [ ]:
s1=pd.Series(['a',2,3,'d'],index=['a',2,'c','d'])

## DataFrame

In [ ]:
p1=pd.DataFrame()
print(p1)

Empty DataFrame
Columns: []
Index: []


In [ ]:
data=[['Tom',10,1.2],['James',20,3.5],['Ricky',30,4.2],['Vin',40,4.4]]
df=pd.DataFrame(data,columns=['Name','Age','Rating'])
print(df)

    Name  Age  Rating
0    Tom   10     1.2
1  James   20     3.5
2  Ricky   30     4.2
3    Vin   40     4.4


In [ ]:
df[0:1]

Name   Age
0  raj  30.0

In [1]:
df1=pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
df2=pd.DataFrame([[5,6],[7,8]],columns=['a','b'])

df1=df1.append(df2)
df1

NameError: ignored

In [ ]:
print(df1.loc[0])

   a  b
0  1  2
0  5  6


In [ ]:
print(df.axes,end='\n\n***************\n')
print(df.dtypes,end='\n\n***************\n')
print(df.empty,end='\n\n***************\n')
print(df.T,end='\n\n***************\n')
print(df.ndim,end='\n\n***************\n')
print(df.shape,end='\n\n***************\n')
print(df.size,end='\n\n***************\n')
print(df.values,end='\n\n***************\n')
print(df.sum(),end='\n\n***************\n')
print(df.mean(),end='\n\n***************\n')

[RangeIndex(start=0, stop=4, step=1), Index(['Name', 'Age', 'Rating'], dtype='object')]

***************
Name       object
Age         int64
Rating    float64
dtype: object

***************
False

***************
          0      1      2    3
Name    Tom  James  Ricky  Vin
Age      10     20     30   40
Rating  1.2    3.5    4.2  4.4

***************
2

***************
(4, 3)

***************
12

***************
[['Tom' 10 1.2]
 ['James' 20 3.5]
 ['Ricky' 30 4.2]
 ['Vin' 40 4.4]]

***************
Name      TomJamesRickyVin
Age                    100
Rating                13.3
dtype: object

***************
Age       25.000
Rating     3.325
dtype: float64

***************


In [ ]:
def addr(el1,el2):
  return el1+el2
df[['Age','Rating']].pipe(addr,3)

Age  Rating
0   13     4.2
1   23     6.5
2   33     7.2
3   43     7.4

In [ ]:
df[['Age','Rating']].apply(np.mean,axis=1)

0     5.60
1    11.75
2    17.10
3    22.20
dtype: float64

In [ ]:
df[['Age','Rating']].pipe(lambda x,y:x*y,100)

Age  Rating
0  1000   120.0
1  2000   350.0
2  3000   420.0
3  4000   440.0

In [ ]:
df[['Age','Rating']].applymap(lambda x:x*100)

Age  Rating
0  1000   120.0
1  2000   350.0
2  3000   420.0
3  4000   440.0

In [ ]:
df_reindexed= df.reindex(index=[0,2,5],columns=['Name','old','Marks'])
df_reindexed

Name  old  Marks
0    Tom  NaN    NaN
2  Ricky  NaN    NaN
5    NaN  NaN    NaN

In [ ]:
df

Name  Age  Rating
0    Tom   10     1.2
1  James   20     3.5
2  Ricky   30     4.2
3    Vin   40     4.4

In [ ]:
data=[['Tom',10,1.2],['James',20,3.5],['Ricky',30,4.2],['Vin',40,4.4]]
df2=pd.DataFrame(data,columns=['FName','Age1','Rating1'])
df1=pd.DataFrame(data,columns=['Name','Age','Rating'])
df1.reindex_like(df2)

FName  Age1  Rating1
0    NaN   NaN      NaN
1    NaN   NaN      NaN
2    NaN   NaN      NaN
3    NaN   NaN      NaN

In [ ]:
df.rename(columns={'Name':'Fname','Age':'Old','Rating':'Score'},
          index={0:'apple',1:'banana'})

Fname  Old  Score
apple     Tom   10    1.2
banana  James   20    3.5
2       Ricky   30    4.2
3         Vin   40    4.4

In [ ]:
for row_index,row in df.iterrows():
  print("{} --  {}".format(row_index,row))

0 --  Name      Tom
Age        10
Rating    1.2
Name: 0, dtype: object
1 --  Name      James
Age          20
Rating      3.5
Name: 1, dtype: object
2 --  Name      Ricky
Age          30
Rating      4.2
Name: 2, dtype: object
3 --  Name      Vin
Age        40
Rating    4.4
Name: 3, dtype: object


In [ ]:
df['Name'].str.get_dummies()

James  Ricky  Tom  Vin
0      0      0    1    0
1      1      0    0    0
2      0      1    0    0
3      0      0    0    1

In [ ]:
s=pd.Series(['Tom','Tak sat', 'John@X', np.nan,'123' ])
s.str.cat(sep='_')

'Tom_Tak sat_John@X_123'

In [ ]:
s.str.get_dummies()

123  John@X  Tak sat  Tom
0    0       0        0    1
1    0       0        1    0
2    0       1        0    0
3    0       0        0    0
4    1       0        0    0

In [ ]:
s.str.contains(' ')

0    False
1     True
2    False
3      NaN
4    False
dtype: object

In [ ]:
s.str.repeat(2)

0            TomTom
1    Tak satTak sat
2      John@XJohn@X
3               NaN
4            123123
dtype: object

In [ ]:
s.str.find('o')

0    1.0
1   -1.0
2    1.0
3    NaN
4   -1.0
dtype: float64

In [ ]:
s.str.isnumeric()

0    False
1    False
2    False
3      NaN
4     True
dtype: object

In [ ]:
pd.get_option("max_rows")

60

In [ ]:
df=df.rename({key:key+2 for key in range(4)})


In [ ]:
df.iloc[0:2,:2]

Name  Age
2    Tom   10
3  James   20

In [ ]:
df

Name  Age  Rating
2    Tom   10     1.2
3  James   20     3.5
4  Ricky   30     4.2
5    Vin   40     4.4

In [ ]:
df.loc[:2,'Name']

2    Tom
Name: Name, dtype: object

In [ ]:
df.iloc[:2,:2]

Name  Age
2    Tom   10
3  James   20

In [ ]:
df['Rating']

2    1.2
3    3.5
4    4.2
5    4.4
Name: Rating, dtype: float64

In [ ]:
data=[[0.1,0.5,0.9],[0.2,0.4,1],[0.3,0.6,1.1],[0.7,0.8,1.2]]
df=pd.DataFrame(data,columns=['A','B','C'])
df

A    B    C
0  0.1  0.5  0.9
1  0.2  0.4  1.0
2  0.3  0.6  1.1
3  0.7  0.8  1.2

In [ ]:
df.rolling(window=3).mean()

A    B    C
0  NaN  NaN  NaN
1  NaN  NaN  NaN
2  0.2  0.5  1.0
3  0.4  0.6  1.1

In [ ]:
df.expanding(min_periods=3).mean()

A      B     C
0    NaN    NaN   NaN
1    NaN    NaN   NaN
2  0.200  0.500  1.00
3  0.325  0.575  1.05

In [ ]:
df.ewm(com=0.5).mean()

A         B         C
0  0.100000  0.500000  0.900000
1  0.175000  0.425000  0.975000
2  0.261538  0.546154  1.061538
3  0.557500  0.717500  1.155000

In [ ]:
r=df.rolling(window=3, min_periods=1)
r.aggregate([np.sum,np.mean])

A          B          C      
   sum  mean  sum  mean  sum  mean
0  0.1  0.10  0.5  0.50  0.9  0.90
1  0.3  0.15  0.9  0.45  1.9  0.95
2  0.6  0.20  1.5  0.50  3.0  1.00
3  1.2  0.40  1.8  0.60  3.3  1.10

In [ ]:
df

A    B    C
0  0.1  0.5  0.9
1  0.2  0.4  1.0
2  0.3  0.6  1.1
3  0.7  0.8  1.2

In [8]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f',
'h'],columns=['one', 'two', 'three'])
df=df.reindex(['a','b','c','d','e','f','g','h'])
df

one       two     three
a  0.295146  1.514013  1.494468
b       NaN       NaN       NaN
c -0.517524  1.481537 -1.101083
d       NaN       NaN       NaN
e  0.593836  0.345746  0.390584
f  0.480397 -0.323482 -1.227641
g       NaN       NaN       NaN
h  0.119622  0.233870 -0.354719

In [11]:
df.notnull().sum()

one      5
two      5
three    5
dtype: int64

In [5]:
df1=pd.DataFrame({'one':[1,2]})
df2=pd.DataFrame({'one':[2,3]})
df3=pd.DataFrame({'two':[2,3]})

In [7]:
df_cat=pd.concat([df1,df2,df3],axis=0)
df_cat

one  two
0  1.0  NaN
1  2.0  NaN
0  2.0  NaN
1  3.0  NaN
0  NaN  2.0
1  NaN  3.0

In [ ]:
df1.append([df2,df3])

one  two
0  1.0  NaN
1  2.0  NaN
0  2.0  NaN
1  3.0  NaN
0  NaN  2.0
1  NaN  3.0

In [ ]:
df1.append(df2)

one
0    1
1    2
0    2
1    3

In [ ]:
pd.bdate_Range('1/1/2011',5)

AttributeError: ignored